<CustomLabel@Label>:
    text_size: self.size
    valign: "middle"
    padding_x: 5

<Input@TextInput>:
    multiline: False

<GreyButton@Button>:
    background_color: 1, 1, 1, 1
    size_hint_y: None
    height: self.parent.height * 0.120

ScreenManager:
    id: screen_manager
    SurveyScreen:
        id: survey_screen
        name: 'survey'
        manager: 'screen_manager'
    ResultScreen:
        id: result_screen
        name: 'result'
        manager: 'screen_manager'
        year_text: survey_screen.year
        events_text: survey_screen.events
    ConfirmationScreen:
        id: confirmation_screen
        name: 'confirmation'
        manager: 'screen_manager'

<SurveyScreen>:
    GridLayout:
        cols: 2
        padding : 30,30
        spacing: 20, 20
        row_default_height: '30dp'
        Label:
            text: '男性'
            text_size: self.size
            valign: "middle"

        CheckBox:
            group: 'check'
            id : chk_male

        Label:
            text: '女性'
            text_size: self.size
            valign: 'middle'

        CheckBox:
            group: 'check'
            id: chk_female

        CustomLabel:
            text: '何年生ですか？'
            text_size: self.size
            valign: 'middle'

        Input:
            id: year

        CustomLabel:
            text: '何の部活に入っていますか？'
            text_size: self.size
            valign: 'middle'

        Input:
            id: no_of_events

        GreyButton:
            text: '完了'
            on_press: root.insert_data(year, no_of_events)
            on_press: app.root.current = 'result'

        GreyButton:
            text: 'キャンセル'
            on_press: app.root.stop

        GreyButton:
            text: '結果'
            on_press: app.root.current = 'result'


<ResultScreen>:
    GridLayout:
        cols: 2
        padding : 30,30
        spacing: 20, 20
        row_default_height: '30dp'
        CustomLabel:
            text:'何年生ですか？'
            # goes to the root "ResultsScreen" and gets attribute year_text
        Label:
            text: root.year_text

        CustomLabel:
            text:'何の部活に入っていますか'
            # goes to the root "ResultsScreen" and gets attribute events_text
        Label:
            text: root.events_text
        Button:
            text: 'Back to survey'
            on_press: app.root.current = 'survey'
        Button:
            text: 'Submit'
            on_press: app.root.current = 'confirmation'
            on_press: root.submit_data(root.year_text, root.events_text)


<ConfirmationScreen>:
    GridLayout:
        CustomLabel:
            text: "Survey Submitted!"
